version: '3.4'

services:
  cultsim-help-guide-be:
    image: cultsim-help-guide-be
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 4000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]