version: '3.4'

services:
  cultsim-help-guide-be:
    image: cultsim-help-guide-be
    build: .
    environment:
      NODE_ENV: production
      NEO4J_URI: bolt://neo4j:7687
    ports:
      - 4000:4000
    depends_on: 
      - neo4j
  neo4j:
    image: neo4j:3.5.21
    ports: 
      - 7474:7474
      - 7687:7687
    environment: 
      NEO4J_AUTH: neo4j/neo4jTest
      NEO4J_dbms_default__advertised__address: neo4j
    volumes:
      - C:\Users\alesc\Desktop\Neo4j\import:/var/lib/neo4j/import    